global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'uaal'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8000', '127.0.0.1:8000']
    metric_relabel_configs:
      # drop very high cardinality labels if needed in future
      - source_labels: [__name__]
        regex: 'process_.*'
        action: drop

rule_files:
  - /etc/prometheus/alert.rules.yml
